First pass at pipeline migration
Signed-off-by: Chris Scott-Thomas <chris.scott-thomas@infinityworks.com>

diff --git a/ci/generate-snapshots/meta-generate-snapshots.yml b/ci/generate-snapshots/meta-generate-snapshots.yml
--- a/ci/generate-snapshots/meta-generate-snapshots.yml
+++ b/ci/generate-snapshots/meta-generate-snapshots.yml
@@ -7,13 +7,10 @@ meta-generate-snapshots:
         image_resource:
           type: docker-image
           source:
-            repository: ((docker-python-boto-behave.repository))
-            version: ((docker-python-boto-behave.version))
-            tag: ((docker-python-boto-behave.version))
+            repository: ((dataworks.docker_python_boto_behave_repository))
+            tag: ((dataworks.docker_python_boto_behave_version))
         params:
-          AWS_DEFAULT_PROFILE: ci
-          AWS_SHARED_CREDENTIALS_FILE: ../../.aws/credentials
-          AWS_CONFIG_FILE: ../../.aws/config
+          AWS_REGION: ((dataworks.aws_region))
           E2E_TEST_TIMEOUT: 300
         run:
           dir: aws-dataworks-e2e-framework
@@ -21,6 +18,8 @@ meta-generate-snapshots:
           args:
             - -exc
             - |
+              source /assume-role
+              set +x
               export E2E_FEATURE_TAG_FILTER="@admin-generate-${SNAPSHOT_TYPE}-snapshots"
               cd src/runners
               ./run-ci.sh \
@@ -43,50 +42,49 @@ meta-generate-snapshots:
         image_resource:
           type: docker-image
           source:
-            repository: ((docker-awscli.repository))
-            version: ((docker-awscli.version))
-            tag: ((docker-awscli.version))
+            repository: ((dataworks.docker_awscli_repository))
+            tag: ((dataworks.docker_awscli_version))
         params:
-          AWS_DEFAULT_PROFILE: ci
-          AWS_SHARED_CREDENTIALS_FILE: .aws/credentials
-          AWS_CONFIG_FILE: .aws/config
+          AWS_REGION: ((dataworks.aws_region))
         run:
           path: sh
           args:
-          - -exc
-          - |
-            if [[ "${TYPE}" == "htme_output" ]]; then
-                S3_BUCKET=$(cat terraform-output-internal-compute/outputs.json | jq -r '.htme_s3_bucket.value.id')
-                S3_PREFIX=$(cat terraform-output-internal-compute/outputs.json | jq -r '.htme_s3_folder.value.id')
-                TODAYS_DATE=$(date '+%Y-%m-%d')
-                S3_PREFIX_FULL="${S3_PREFIX}/${TODAYS_DATE}"
-            elif [[ "${TYPE}" == "htme_manifest" ]]; then
-                S3_BUCKET=$(cat terraform-output-ingest/outputs.json | jq -r '.s3_buckets.value.input_bucket')
-                S3_PREFIX_FULL=$(cat terraform-output-internal-compute/outputs.json | jq -r '.manifest_s3_prefixes.value.export')
-            else
-              echo "Invalid type of '${TYPE}'"
-              exit 1
-            fi
+            - -exc
+            - |
+              source /assume-role
+              set +x
+              if [[ "${TYPE}" == "htme_output" ]]; then
+                  S3_BUCKET=$(cat terraform-output-internal-compute/outputs.json | jq -r '.htme_s3_bucket.value.id')
+                  S3_PREFIX=$(cat terraform-output-internal-compute/outputs.json | jq -r '.htme_s3_folder.value.id')
+                  TODAYS_DATE=$(date '+%Y-%m-%d')
+                  S3_PREFIX_FULL="${S3_PREFIX}/${TODAYS_DATE}"
+              elif [[ "${TYPE}" == "htme_manifest" ]]; then
+                  S3_BUCKET=$(cat terraform-output-ingest/outputs.json | jq -r '.s3_buckets.value.input_bucket')
+                  S3_PREFIX_FULL=$(cat terraform-output-internal-compute/outputs.json | jq -r '.manifest_s3_prefixes.value.export')
+              else
+                echo "Invalid type of '${TYPE}'"
+                exit 1
+              fi
 
-            S3_LOCATION="s3://${S3_BUCKET}/${S3_PREFIX_FULL}/" 
-            TIMEOUT=3600
-            
-            aws s3 rm "${S3_LOCATION}" --recursive
+              S3_LOCATION="s3://${S3_BUCKET}/${S3_PREFIX_FULL}/" 
+              TIMEOUT=3600
 
-            TIME_TAKEN=1
-            while true; do
-                if [[ ${TIME_TAKEN} > ${TIMEOUT} ]]; then
-                    break
-                fi
+              aws s3 rm "${S3_LOCATION}" --recursive
 
-                if [[ -z $(aws s3 ls "${S3_LOCATION}") ]]; then
-                    break
-                fi
+              TIME_TAKEN=1
+              while true; do
+                  if [[ ${TIME_TAKEN} > ${TIMEOUT} ]]; then
+                      break
+                  fi
 
-                TIME_TAKEN=$((TIME_TAKEN + 1))
-                sleep 1
-            done
+                  if [[ -z $(aws s3 ls "${S3_LOCATION}") ]]; then
+                      break
+                  fi
+
+                  TIME_TAKEN=$((TIME_TAKEN + 1))
+                  sleep 1
+              done
         inputs:
-        - name: .aws
-        - name: terraform-output-ingest
-        - name: terraform-output-internal-compute
+          - name: .aws
+          - name: terraform-output-ingest
+          - name: terraform-output-internal-compute
